### ISSUE TITLE
Undefined offset error if no job type set

### ISSUE THREAD

**Issue by tomslominski** [stevenkellow/wpjm-schema#2]
Hi. I'm getting an undefined offset error on line 118 of patch-functions.php, because some of my job listings don't have a type set. It's an easy fix, so I'm happy to submit a pull request or post the changes here if you want? I just don't want my fix in the plugin to be overwritten should there be an update in the future :)

**Comment by stevenkellow** [comment]
Hi Tom, if you're happy to submit a pull request that would be great, thanks very much!

**Comment by tomslominski** [comment]
Cool, I've created one here https://github.com/stevenkellow/wpjm-schema/pull/3

**Comment by stevenkellow** [comment]
Fantastic, thanks very much!
